name: CI with Dependency Cache

on:
  push:
    branches: [main]
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Dependency cache
      - name: prime-cache-58e4f82
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-58e4f82
          restore-keys: cache-58e4f82

      # Step 4: Install dependencies (skipped if none)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, skipping install"
          fi

      # Step 5: Run any scripts / tests
      - name: Run scripts
        run: echo "This is where you can run your Python scripts or tests"

      # Step 6: Show cache result
      - name: Show cache result
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
